### ISSUE TITLE
Contact Housing Resources Persistence

### ISSUE THREAD

**Issue by adriannadiaz** [adriannadiaz/SocialWorker#14]
As a social worker, I want to be able to keep track of contacted resources through a participant's log. (backend)

Priority [Med]
USP [3]

**Tasks**
- [x] Create an entry in database with id of participant, status of request, text field for notes, an dictionary of ids of housing resources as key and a an array consisting of [status  as value 
- [x] Be able to return all entries in the database 
- [x] The ability to return a single entry by id of participant
- [x] Be able to delete entries in case of an accident, normal workflow does not encourage the deletion of this.
