### ISSUE TITLE
Assign Participant to Housing Persistance

### ISSUE THREAD

**Issue by adriannadiaz** [adriannadiaz/SocialWorker#15]
As a social worker, working with  a participant looking for urgent housing, I want to be able to track a participant's housing status in the database (backend).

**Tasks**
- [x] Be able to record changes in the status of a participant in their housing case
- [x] Be able to return a housing case based on either participant id or housing id
- [x] Be able to return all housing cases for a participant based on their id
- [x] Be able to delete a housing case (use with care)
