### ISSUE TITLE
Social Worker Account Management

### ISSUE THREAD

**Issue by adriannadiaz** [adriannadiaz/SocialWorker#16]
As a social worker, I want to guarantee that the particpant records are confidential and are only accessed by other authorized social workers.

Priority: [Low]
USP: [5]

**Tasks**
- [x] Leverage the User collection to manage the login information for social workers @francisbouchard 
- [x] Implement a "signup" / "add social worker" page
- [x] Implement a login page
- [x] Make sure that the website and its routes are only accessible with authentication
- [x] Mongodb cleanup: get rid of redundant collections
- [x] Make sure index page redirects to login page

**Comment by Ldhatter** [comment]
I removed "- [ ] Implement a login page
- [ ] Make sure that the website and its routes are only accessible with authentication"

because this should have really been part of the authentication ticket @adriannadiaz @francisbouchard  so let's complete that within the PR for authentication
