### ISSUE TITLE
Add New Participant

### ISSUE THREAD

**Issue by Ldhatter** [adriannadiaz/SocialWorker#2]
As a social worker, working with a participant looking for urgent housing, I want to create a new participant profile

Priority [High]
USP [13]

**Tasks**

1. new participant: create profile form (10h)
frontend: @Ldhatter	
backend:	 @annarog @francisbouchard 	

2. View participant profiles (4h)
frontend: @wahabwajahat 
backend: @annarog @francisbouchard 

**other tasks:**
- [x] create architecture diagrams (2 h)
- [x] setting up frontend (angular client) (6 h)
- [x] setting up express (1 h)
- [x] setting up travis ci (1 h)
- [x] setting up mongo @jtalarico (2 h)
- [x] setting up docker @adriannadiaz (2 h)
- [x] backend APIs @annarog (2 h)
- [x] testing

**Comment by rigbypc** [comment]
These stories are epics. Please break them down into smaller units. Presumably you have the story where you create a new "participant" the story where you input potential "urgent houses" the story where you assign a "participant to a house"
