### ISSUE TITLE
Add Notes

### ISSUE THREAD

**Issue by Ldhatter** [adriannadiaz/SocialWorker#30]
As a social worker, I want to be able to keep track of my participant notes 

[USP] : 5
[PRIORITY] : MED

This includes digitizes artefacts and user text input in the site.

**TASKS**

**Frontend**
- [x]  Button in profile to open modal to add notes
- [x]  Modal component that includes form to add notes
- [x]  Functionality to add image of notes
- [x]  Notes service provider

**Test**
- [x] Frontend component tests
- [x] ~~Frontend service tests~~ this was done in Anna's branch for profile service

**Comment by Ldhatter** [comment]
Fix: Handling large files
------------------------------------------------------------
Related to #32 Participant profile history
- [ ] Allow for files larger than 40KB
- [ ] Warn user if files exceed this size

**Comment by Ldhatter** [comment]
Bug: Add Notes does not reload once note is added
---------------------------------------------------------------------------

- [ ] Once user adds a note, make it automatically display in the profile
