### ISSUE TITLE
Participant profile history 

### ISSUE THREAD

**Issue by adriannadiaz** [adriannadiaz/SocialWorker#32]
As a social worker, I want to view the history of participant logged records 

[USP] : 3
[PRIORITY] : MED

**TASKS**

**Frontend**
- [x]  Have a reverse chronological list of entries
- [x]  Display attachments in each note
- [x]  Deleting entries (Adding is covered in ticket #30)

**Backend**
- [x] Add route for deleting a participant's note

**Test**
- [x] Route for deleting a note (backend)
- [x] Displaying and deleting notes (frontend)
