### ISSUE TITLE
Add Documents

### ISSUE THREAD

**Issue by annarog** [adriannadiaz/SocialWorker#33]
As a social worker, I want to be able to upload participant documents (digitized artifacts).

Priority: [Med]
USP: [3]

**Tasks**
- [x] Frontend add documents component 
    - [x] Frontend: "add document" button + modal
    - [x] Frontend: "documents" viewable in profile
    - [x] Frontend: "delete document" 
- [x] Frontend add service provider
- [x] Refactor: change from using blobs to using filepaths @francisbouchard 
- [x] Backend: refactor any changes needed to the model 
- [ ] Tests: frontend component
- [ ] Tests: frontend services
- [ ] Tests: backend update tests if needed

Related to #30

**Comment by Ldhatter** [comment]
Note: refactor to allow larger documents (pdf, image etc)

**Comment by Ldhatter** [comment]
**Note: We may want to refactor the service providers in the future.**

Similarly to the casefile service provider, we can place crud functionality for documents and notes in their own service providers.

**Comment by Ldhatter** [comment]
@francisbouchard  im placing the error messages here 

so it does not upload. and does not display on the frontend (only blank). 
this is what i get (with a file less than 40kb)

"ENOENT: no such file or directory, mkdir '/Users/liuai/Documents/_soen490/SocialWorker/express-server/documents/b123'"
 

![screen shot 2018-02-11 at 4 14 52 pm](https://user-images.githubusercontent.com/13111600/36078608-1b314286-0f47-11e8-80be-7d3b3d9c3c30.png)
![screen shot 2018-02-11 at 4 15 25 pm](https://user-images.githubusercontent.com/13111600/36078609-1b3e5e62-0f47-11e8-9336-bda6fad9646f.png)


![screen shot 2018-02-11 at 4 18 01 pm](https://user-images.githubusercontent.com/13111600/36078612-281d0926-0f47-11e8-9d06-edc723cc3d28.png)
