### ISSUE TITLE
Validation for forms

### ISSUE THREAD

**Issue by Ldhatter** [adriannadiaz/SocialWorker#37]
As a user I want the application to warn me and stop me from submitting a form with invalid inputs.

Linked with issues #2, #5, #30, #33

USP: 3
Priority: High
Risk: High

**Tasks**
- [x] Decide on form style (comment below which one + why)
    - [Template](https://angular.io/guide/forms) or
    - [Reactive](https://angular.io/guide/reactive-forms) **this one** 
- [x] Create validators module for forms [Form validators](https://angular.io/guide/form-validation)
- [x] Apply validation to new participant
- [x] Apply validation to edit participant (done in master)
- [x] Apply validation to new resource
- [x] Apply validation to edit resource
- [x] Test validators
- [x] For Participant make it mandatory to only have at least one of the fields filled in, it can be telephone OR email OR social media OR physical address... 
- [x] For Resource it has to be mandatory for the Term to be filled in. Currently this validation does not happen in the frontend. Housing resource is sent to the backend, not saved because it fails validation there, but nevertheless the user is told that the resource was added when in fact it wasn't...

***Research***
_I went back to research more on the different styles of forms (Liuai)_

Template:
- asynchronous (disadvantage: timing issues)
- less code in the component class
- but complicated unit testing due to the async 
- mutable data model 
- Angular creates the form control objects 
- Angular does the binding to data model via using ngModel

Reactive:
- synchronous (advantage: it is under your control)
- immutable data model
    - Component extracts user changes, forwards it to external component or service, returns a new data model to the component that reflects the updated model state
- You create and manipulate form control objects directly in the component class.
- You can push data model values into the form controls and pull user-changed values back out
- you create the entire form control tree in code

Usefule links:
[API Controls](https://angular.io/api/forms/AbstractControl)
[API Validators](https://angular.io/api/forms/Validators)
[Example](https://stackblitz.com/angular/xbgpkpjrxkl?file=src%2Fapp%2Freactive%2Fhero-form-reactive.component.html)

**Comment by wahabwajahat** [comment]
Linked with PR #39

**Comment by adriannadiaz** [comment]
What about backend ?

**Comment by adriannadiaz** [comment]
Not *all* fields are required. Clicking on a field does not make it required. Only filled fields are to be validated. 
For resources only name and term are required fields
For participant only name and username are required fields.

**Comment by Ldhatter** [comment]
![screen shot 2018-03-04 at 2 06 44 pm](https://user-images.githubusercontent.com/13111600/36949376-61613aa8-1fb5-11e8-918e-551f5cd50f74.png)
![screen shot 2018-03-04 at 2 06 50 pm](https://user-images.githubusercontent.com/13111600/36949377-619a4d48-1fb5-11e8-81a6-14286a10f0cb.png)
