### ISSUE TITLE
Dashboard Landing

### ISSUE THREAD

**Issue by adriannadiaz** [adriannadiaz/SocialWorker#48]
The application upon logging in will have a dashboard view for the frontline workers,populated with little widgets.

USP: 5
Priority: High
Risk: Low

**Tasks**
- [x] Wireframe page (upload image here)
- [x] Add sidenav
- [x] Casefile activity: Add list of current cases
- [x] ~Casefile activity: Add time-aware tracking of case files~
- [x] Recent activity: casefiles and phone logs
- [x] ~Participant activity: Add list of their most recently updated participants~
- [x] Tasks: user task list (private to each user)
- [x] ~Tasks: global agenda (visible for all users, what they have to do for the day).~
- [x] Phonelog: add in phonelog component (needs #66, #67)
- [x] Reports: add in placeholder component (for #90)
- [x] Trash: add in tashbin component (needs #65)
- [x] Admin: add in manage accounts component (uses #63)
- [x] Test: update frontend
- [x] Test: update backend

**Comment by Ldhatter** [comment]
Layout
---

_If user is an admin, then user can also access manage users, all casefiles, all tasks. If user is not an admin, then user does not see manage users, all assigned casefiles, all tasks(?)_

![dashboard_admin-casefiles](https://user-images.githubusercontent.com/13111600/37247328-60468c64-2487-11e8-91bb-1cc3b8b72e8e.jpg)
![dashboard_admin-main](https://user-images.githubusercontent.com/13111600/37247329-605e7d42-2487-11e8-9d83-3c4ec07d9709.jpg)

**Comment by Ldhatter** [comment]
Note mat-sidenav
--

material sidenav seems to have recent bugs and does not seem to be working properly.

**Comment by Ldhatter** [comment]
Questions for Assteq
-----
- Sometimes multiple workers are meeting the same participant. Do they also have multiple people working on a case file? If so would they benefit from seeing/knowing all  who's working on the same case file? (therefore have in the model: createBy, updatedBy, and an array of all assigned users)

**Comment by Ldhatter** [comment]
Nice-to-have
----

- 'Follow up' date for Participants for this to be able to be showed on the Dashboard eventually.
