### ISSUE TITLE
Contact Housing Resources Form

### ISSUE THREAD

**Issue by Ldhatter** [adriannadiaz/SocialWorker#5]
As a social worker, I want to be able to keep track of contacted resources through participant's profile. (frontend)

Priority [High]
USP [5]

**Tasks**

- [x] Initialize case (includes status, date initiated, deadline, priority)
- [x] Track which resources were contacted for that participant, through a list of housing resources
- [x] Have a text field for notes regarding the ticket for housing
