### ISSUE TITLE
Assign Participant to Housing Form

### ISSUE THREAD

**Issue by Ldhatter** [adriannadiaz/SocialWorker#6]
As a social worker, working with a participant looking for urgent housing, I want to be able to assign housing via a form. (frontend)

Priority [High]
USP [3]

**Tasks**
- [x] Display all cases for a given participant
- [x] Create checkbox, date input, and note input per resource to contact.
- [x] Adjust UI for contact resource grid. 
- [x] Update the service/routes to send this data to the db
- [x] In an open case: create `select` to choose which housing resource the participant will be staying at and 
- [x] Complete case (changes status, and keeps case in history) 
- [x] Delete case (completely removes case from history)
- [x] Testing in frontend
- [x] Testing in backend
  

THIS IS BLOCKED BY #5

**Comment by Ldhatter** [comment]
This is blocked by #5

**Comment by Ldhatter** [comment]
TODO: casefile should have a title or type or kind 
-----
Example "Find Urgent Housing" or "Urgent Housing"

- [ ] Add this to models
- [ ] edit html to display case title

**Comment by Ldhatter** [comment]
TODO: edit casefile tests in backend so that the test data matches changes to casefile model
----
- [ ] fix tests
- [ ] check travis passes
