### ISSUE TITLE
Add Different Types of Resources

### ISSUE THREAD

**Issue by annarog** [adriannadiaz/SocialWorker#62]
As a user, I would like to add different types of resources to the system.

Priority: [Med]
USP: [5]

***Add Different Types of Resources, as String.***
In the frontend they should be selected from a dropdown menu.
Not all fields from the Housing Resources apply so this is a major overhaul.
Make it as extendable as possible! (ie: if the social worked wants to add a new type of resource, it shouldn't break everything)

**Tasks:**
- [x] Find common fields of resources, and fields that would differ
- [x] Refactor hierarchy for resources in the backend to include new types of resources
- [ ] Refactor frontend services to be used for all types of resources
- [ ] Add select dropdown in the _Add Resources_ page to choose from types of resources
- [ ] Depending on the resource, update necessary frontend fields that would be needed as inputs
- [ ] ~Allow an option to create custom fields. This includes a key (text) + value (text) pair. The backend: resource would have an array of custom fields. Eg: Custom: [ { key: 'Some custom key', value: 'Value for this key'}, { key: 'Name of lawer', value: 'Sheila Dusseldorf'} ]~
- [x] Refactor the frontend that displays all the resource cards. 
- [ ] Tests

_Types of Resources_:
- [x] Housing / Shelter
- [x] **Medical / Hormones** Do this first
- [ ] Legal / Tickets
- [ ] General Accompaniment 
- [ ] Financial
- [ ] Name Change 
- [ ] Food Security (Name of Organization, Address, Schedule)
- [ ] Job Finding (Name of contact, Email)
- [ ] Immigration (Email, Address, Phone, Name of Lawyer/Firm)
- [ ] Victims of Violence
- [ ] Sexual Health (Address, Phone, Name of Doctor)
- [ ] Web Resources (URLS + descriptor)

Once this is done, then populate Database with a few Resources of all of the types above...

**Comment by adriannadiaz** [comment]
**Medical:**
  without_cost: boolean
  time_accessibility: String
  requires_extensive_time

**Comment by wahabwajahat** [comment]
![capture](https://user-images.githubusercontent.com/14875425/37568982-dd311560-2ab2-11e8-854f-21ae83d6e91e.JPG)

This is on a loop @adriannadiaz ?
