### ISSUE TITLE
Managing User Accounts

### ISSUE THREAD

**Issue by Ldhatter** [adriannadiaz/SocialWorker#63]
As an admin user, I want to view and manage all other users' accounts. (including the creation of additional admin accounts)

USP [3]
Priority [High]

**Tasks**
- [x] create other admin accounts
- [x] view all users by role 
- [x] assign social workers to participants
- [x] delete user
- [x] Testing
