### ISSUE TITLE
Update Casefile 

### ISSUE THREAD

**Issue by annarog** [adriannadiaz/SocialWorker#64]
As a user, I would like to view, edit, and use casefiles for any type of resource.

Priority: [High]
USP: [2]

**Tasks**

- [x] resource comment functionality to edit text
- [x] ~resource comments change vars and methods with mention of 'note' to 'comment'~ Wont do since resource models are using `note` notation
- [x] casefile selected resource should be editable
- [x] when a casefile is closed, it should display the information as non-editable "text" versus as form inputs, and alternatively when casefile is reopened, it shows as form
- [x] add input to edit casefile type: Example "Find Urgent Housing" or "Urgent Housing". Edit html to display case title. Add this to model. The types should include the others mentioned by Astteq, and also a way to add a new custom type.
- [x] Editable casefile note
- [x] Save updated note
- [x] Selected resource has start and end date 
- [x] update tests (remember to include casefile type)

**Comment by Ldhatter** [comment]
Nice-to-have:
----------------------

- Casefile type in panel header
- Symbol (maybe in red?) to signify urgent in panel header
- When casefile is in progress: Make urgency editable as a button toggle or radio
- When casefile is in progress: Casefile type is editable
- When casefile is in progress: Resources can be added and removed

**Comment by Ldhatter** [comment]
![screen shot 2018-02-20 at 7 55 06 pm](https://user-images.githubusercontent.com/13111600/36457458-130eca96-1678-11e8-9fd7-e0ec865706a7.png)

**Comment by Ldhatter** [comment]
Needs refactoring:
---------------------
- Reactive Forms
- Separating profile components (case files, notes, documents) 
- HTML cleanup
