### ISSUE TITLE
Managing Deleted Records

### ISSUE THREAD

**Issue by Ldhatter** [adriannadiaz/SocialWorker#65]
As an admin user, I'd like to view deleted records and have the option of permanently deleting them or adding them back. 

USP [3]
Priority [Med]

Adding back a record means setting the deleted=false
Begin with the simplest case: delete participant. 

**Tasks**
- [x] Create _trash_ component
- [x] Add navigation option (trash icon) in dashboard 
- [x] Create _trash_ service (get all in trash bin, delete one, delete all)
- [x] Display deleted record in trash bin
- [x] Remove record from trash bin (deletes from db)
- [x] Return record out of trash bin (deleted=false)
- [x] Testing
