### ISSUE TITLE
Logging a phone call

### ISSUE THREAD

**Issue by annarog** [adriannadiaz/SocialWorker#66]
As a user, I would like to log the necessary information of every phone call.

Priority: [Med]
USP: [3]

***Description***
Add PhoneLog Tool for Taking PhoneCalls.

This is a menu option on top. 
Frontline workers field calls about enquiries from either the general public, trans / questioning individuals, or organizations/ companies that deal/ are interested in problems that trans people face. They currently log their calls on paper. At the end of the year, they manually count the calls and get the stats of who called (_type of person_) and the reason of the call (_subject_). These stats are used in order to get funding.
Active phone logs (calls that haven't been replied to) could be also displayed in the dashboard.

_Phone log uses_:
- User who logged (done by system)
- Date logged (done by system)
- User who called back (done by system)
- Date called back (automatically the date of checking off, but can be edited)
- Date
- Phone number
- Language
- Urgent (yes or no)
- Note regarding the call (eg: when to call back)
- Pronoun (if known)
- Name of caller
- Subject (same as resource types)
- Message
- Type of person calling. _keyword examples that were given: transpeople, organization, external person (other), social worker (intervenant)_

**Tasks:**
- [x] Added a new component called phonelog
- [x] Added new mongoose schema phonelog
- [x] Added backend routes for phonelog
- [x] Added frontend classes for phonelog
- [x] Added tabbed browsing and top menu access for phonelog
- [x] Making form for logging phonecall
- [x] Ensuring all fields are working 
- [x] Frontend testing
- [x] Backend testing

**Comment by Ldhatter** [comment]
I  realized I accidentally put the phone logging info in the wrong ticket. So now it's added properly here :)

**Comment by adriannadiaz** [comment]
A PR has been made #73
