### ISSUE TITLE
View Participant Records

### ISSUE THREAD

**Issue by Ldhatter** [adriannadiaz/SocialWorker#68]
****DEADLINE: Wednesday, March 7, 2018****

As a user, I would like to view records. 

view records (document & note) for users (pdf thumbnail, jpg thumbnail, and if user selects then modal opens). For multi-page documents, I want a page dump at 600x800px of every page of the document.

USP [3]
Priority [High]

**Tasks**
- [ ] Find a way to get record file from server
- [ ] Add view Document thumbnail
- [ ] Add view Note thumbnail
- [ ] Add modal component to view larger record (Document or note)
