### ISSUE TITLE
Download Participant Records

### ISSUE THREAD

**Issue by Ldhatter** [adriannadiaz/SocialWorker#69]
****DEADLINE: Wednesday, March 7, 2018****

As a user, I would like to download records. User can download (via button in the profile or in the modal of viewing the thumbnails). 

USP [3]
Priority [Med]

**Tasks**
- [ ] Find a way to retrieve files from server 
- [ ] Create button to download file 
- [ ] In the modal component (should be done in either this ticket or in #68 ) create button to download file
- [ ] Test

**Comment by Ldhatter** [comment]
@JTalarico hey what's happening with this ticket? Do you need some feedback/help/inspiration? If you have any questions, please don't hesitate to post here directly so anyone could try and help you. Also i feel like this ticket is being blocked by ticket #68 and it's PR #76 . That branch doesn't seem to work currently, so if you can help out in the PR by fixing those bugs, then after we pull the newest changes and can try to resolve whatever your stuck on in this ticket. :)
